### ISSUE TITLE
Publish draft release

### ISSUE THREAD

**Issue by csandanov** [xresloader/upload-to-github-release#11]
Hi, thank you for your work, very useful action, I'm migrating from travis and it is very similar to their github deployer, however one thing is missing – is there a way to publish draft release with the file upload

**Comment by owt5008137** [comment]
@csandanov Yes, just set ```draft: true``` . And here is a sample https://github.com/xresloader/upload-to-github-release-test/blob/master/.github/workflows/main.yml .
Hope helpful.

**Comment by csandanov** [comment]
I meant if you already have a drafted release with an associated future tag, so when you  actually create and push the tag you want to publish the associated release after artifacts have been uploaded

**Comment by owt5008137** [comment]
@csandanov 
Thanks for your suggestion, but I didn't understand what does "already have a drafted release with an associated **future tag**" mean? As I known, all github release must be bind to a tag whether it's a draft. If you want to update a drafted release already exists, these setting may be help.

```yaml
jobs:
  build:
    steps:
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*" # file patterns to upload splited by ";"
          draft: false # update it
          tag_name: "The tag name of the drafted release already exists"
```

Using  ```tag_name``` setting can modify a release already exists. But we only try to find the drafted release from the latest 100 releases.

> PS: Before version v1.2.2, this action can not find the existed and drafted release. It's a BUG and I have already updated it into [master](https://github.com/xresloader/upload-to-github-release/tree/master) and [v1](https://github.com/xresloader/upload-to-github-release/tree/v1) branch.
