### ISSUE TITLE
Upload get stuck forever

### ISSUE THREAD

**Issue by patrickelectric** [xresloader/upload-to-github-release#12]
more than 15 minutes trying to upload, got stuck, broke all others builds.
https://github.com/patrickelectric/ping-components/runs/1517505545?check_suite_focus=true

**Comment by owt5008137** [comment]
@patrickelectric There are too many files to upload in your workflow and they exceed the API rate limit of one token.

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          DEPLOY_PATH: pingviewer-Release.dmg
        - os: ubuntu-latest
          DEPLOY_PATH: pingviewer-Release.AppImage
        - os: windows-latest
          DEPLOY_PATH: deploy # This is a directory and it has many files.

    - name: Update continuous release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: continuous
        file: ${{ matrix.DEPLOY_PATH }} # Try to upload the "deploy" directory with too many files
        tags: false
        overwrite: true
        prerelease: true
        verbose: true
```

Maybe it's  better to archive the ```deploy``` into a zip and only upload one file?
