### ISSUE TITLE
Error while uploading: already_exists with overwrite true

### ISSUE THREAD

**Issue by patrickelectric** [xresloader/upload-to-github-release#18]
I'm having the following error message:
```
Upload asset: pingviewer-Release.dmg failed => Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"} HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}     at /Users/runner/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13125:23     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Configuration:
```
    - name: Update continuous release
      uses: xresloader/upload-to-github-release@v1
      if: ${{ github.event_name != 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: continuous
        file: ${{ matrix.DEPLOY_PATH }}
        tags: false
        draft: false
        overwrite: true
        prerelease: true
        verbose: true
```
