### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by liudonghua123** [xresloader/upload-to-github-release#33]
I have a job step like the following.

```yaml
      - name: 'Publish binary to release'
        continue-on-error: true
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          file: ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}*
          tags: true
          draft: false
          overwrite: true
```

When I make a push, I expect this job create a release and push some files. But I got `Try to create release xxx for xxx failed: Resource not accessible by integration` error.

![image](https://user-images.githubusercontent.com/2276718/166856981-36808607-b954-436c-9604-a3599d19efde.png)
