### ISSUE TITLE
FIle to upload not found

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [xresloader/upload-to-github-release#44]
I don't know why but the uploader cannot find my zip which is clearly present in my worklog (attached). 
File path: ` D:\a\Client/Client/build/client-release.zip`
[worklog.txt](https://github.com/xresloader/upload-to-github-release/files/10701392/worklog.txt)

I even hard-coded the path reported by my List step:
```yaml
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.3.9
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: D:\a\Client/Client/build/client-release.zip
        overwrite: true
        # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
        # tags: # optional
        # Only work on these branches(splited by semicolon), set to nothing to accept all branches.
        # branches: # optional
        # With verbose: true, be verbose.
        verbose: true
        # Set custom tag name.
        tag_name: v2.5
        # If try to update latest release.
        update_latest_release: true
        # Set release id to update.If release_id is set, this step will fail if we can not find it.
        # release_id: # optional, default is 
```

My full yaml is attached as well for your convenience:
[windows.yml.txt](https://github.com/xresloader/upload-to-github-release/files/10701410/windows.yml.txt)
