### ISSUE TITLE
Feature Request - delete existing artifacts

### ISSUE THREAD

**Issue by jeacott1** [xresloader/upload-to-github-release#8]
HI, first of all, thanks for this, it works very well.
I'd like an option to be able to clear any existing artifacts from a previously built release before uploading new ones (not just replace existing).

thoughts?

**Comment by owt5008137** [comment]
@jeacott1 Done. you can use ```delete_file: file glob pattern``` to delete old asset files now. For example:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "a-*.txt;b-*.txt;c-*.txt"
          delete_file: "a-*.txt;b-*.txt"
```

If we have old file ```a-1.txt```,```a-2.txt```,```b-1.txt``` before. and we will upload ```a-2.txt```, ```b-2.txt``` and ```c-1.txt``` .
After this action finished, we will only have the new ```a-2.txt``` and ```b-2.txt``` , ```c-1.txt``` in this release.

Here is a sample https://github.com/xresloader/upload-to-github-release-test/blob/master/.github/workflows/release.yml .
